name: Publish Plugin

on:
  workflow_dispatch:
  
  push:
    branches:
      - 'main'
    paths:
      - 'version.properties'
      
jobs:
  build:
    runs-on: ubuntu-latest

    environment: release  

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with Gradle
        env:
          KDBINSIDEBRAINS_RELEASE_PLUGIN_TOKEN: ${{secrets.KDBINSIDEBRAINS_RELEASE_PLUGIN_TOKEN}}
        run: ./gradlew publishPlugin
